### ISSUE TITLE
Il manque un lien vers le site dans le readme!

### ISSUE THREAD

**Issue by cyrilrbt** [mlhamel/estcequeclaudiaaaccouche#1]
Je me souviens plus comment t'ecris le nom de domaine...

**Comment by mlhamel** [comment]
Fixed by https://github.com/mlhamel/estcequeclaudiaaaccouche/commit/d3aa2e7a7d4446ec1aecbb84af1bc9915bda4274

**Comment by cyrilrbt** [comment]
Merci!
